import java.text.SimpleDateFormat;
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JoptionPane;
/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Jframe.java to
edit this template
*/
/**
 *
 * @author JAISHUK REDDY*/
public class issueBook extends javax.swing.Jframe {
    /**
     * Creates new form issueBook
     */
    public issueBook() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the
     form.
     * WARNING: Do NOT modify this code. The content of this method is
     always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked”)
    // <editor-fold defaultstate=”collapsed” desc=”Generated Code”>
    private void initComponents() {
        jLabel1 = new javax.swing.Jlabel();
        jLabel2 = new javax.swing.Jlabel();
        jLabel3 = new javax.swing.Jlabel();
        jLabel4 = new javax.swing.Jlabel();
        jTextField1 = new javax.swing.JtextField();
        jTextField2 = new javax.swing.JtextField();
        jDateChooser1 = new com.toedter.calendar.JdateChooser();
        jDateChooser2 = new com.toedter.calendar.JdateChooser();
        jButton1 = new javax.swing.Jbutton();
        jButton2 = new javax.swing.Jbutton();
        jLabel5 = new javax.swing.Jlabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("Book ID”);
        jLabel2.setText("Student ID”);
        jLabel3.setText("Issue Date");
        jLabel4.setText("Due Date");
        jButton1.setText("Issue Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLabel5.setText("Issue Book");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(

                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD ING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD ING, false).addGroup(layout.createSequentialGroup().addGap(95, 95, 95).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD ING, false).addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(60, 60, 60).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD ING, false).addComponent(jTextField1).addComponent(jTextField2).addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE).addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addGroup(layout.createSequentialGroup().addGap(109, 109, 109).addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jButton2))).addGroup(layout.createSequentialGroup().addGap(177, 177, 177).addComponent(jLabel5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(82, Short.MAX_VALUE))
    );
            layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel5).addGap(29, 29, 29).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jTextField1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASE
                                            LINE).addComponent(jLabel2).addComponent(jTextField2,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3).addComponent(jDateChooser1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAI
                                            LING).addComponent(jLabel4).addComponent(jDateChooser2,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(47, 47, 47).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASE
                                            LINE).addComponent(jButton1).addComponent(jButton2)).addContainerGap(55, Short.MAX_VALUE))
    );
            pack();
            }// </editor-fold>
            private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY”);
        String bookID = jTextField1.getText();
        String studentID = jTextField2.getText();
        String issueDate = dFormat.format(jDateChooser1.getDate());
        String dueDate = dFormat.format(jDateChooser2.getDate());
        String returnBook = "no”;
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from book where bookID = '”+bookID+”’”);
            if(rs.next()){
                ResultSet rs1 = st.executeQuery("select * from student where studentID = '”+studentID+”’”);
                if(rs1.next()){
                    st.executeUpdate("insert into issue values ('"+bookID+"’,'"+studentID+"','"+issueDate+"','”+dueDate+”’,’”+returnBook+”
’)”);
                    JoptionPane.showMessageDialog(null,"Book Successfuly Issued.”);
                    setVisible(false);
                    new issueBook().setVisible(true);
                }
                else{
                    JoptionPane.showMessageDialog(null,"Incorrect Student ID !!!");
                }
            }
            else{
                JoptionPane.showMessageDialog(null,"Incorrect Book ID
                !!!");
            }
        }catch(Exception e){
            JoptionPane.showMessageDialog(null,"Exception caught : " + e);
            setVisible(false);
            new issueBook().setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate=”collapsed” desc=” Look and feel
        setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with
the default look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {if ("Nimbus".equals(info.getName())) {

                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
            }
        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueBook().setVisible(true);
            }
        });
    }
    // Variables declaration – do not modify
    private javax.swing.Jbutton jButton1;
    private javax.swing.Jbutton jButton2;
    private com.toedter.calendar.JdateChooser jDateChooser1;
    private com.toedter.calendar.JdateChooser jDateChooser2;
    private javax.swing.Jlabel jLabel1;
    private javax.swing.Jlabel jLabel2;
    private javax.swing.Jlabel jLabel3;
    private javax.swing.Jlabel jLabel4;
    private javax.swing.Jlabel jLabel5;
    private javax.swing.JtextField jTextField1;
    private javax.swing.JtextField jTextField2;
    // End of variables declaration
}
