import java.text.SimpleDateFormat;
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JoptionPane;
/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Jframe.java to
edit this template
*/
/**
 *
 * @author JAISHUK REDDY*/
public class issueBook extends javax.swing.Jframe {
    /**
     * Creates new form issueBook
     */
    public issueBook() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the
     form.
     * WARNING: Do NOT modify this code. The content of this method is
     always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked”)
    // <editor-fold defaultstate=”collapsed” desc=”Generated Code”>
    private void initComponents() {
        jLabel1 = new javax.swing.Jlabel();
        jLabel2 = new javax.swing.Jlabel();
        jLabel3 = new javax.swing.Jlabel();
        jLabel4 = new javax.swing.Jlabel();
        jTextField1 = new javax.swing.JtextField();
        jTextField2 = new javax.swing.JtextField();
        jDateChooser1 = new com.toedter.calendar.JdateChooser();
        jDateChooser2 = new com.toedter.calendar.JdateChooser();
        jButton1 = new javax.swing.Jbutton();
        jButton2 = new javax.swing.Jbutton();
        jLabel5 = new javax.swing.Jlabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("Book ID”);
        jLabel2.setText("Student ID”);
        jLabel3.setText("Issue Date");
        jLabel4.setText("Due Date");
        jButton1.setText("Issue Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLabel5.setText("Issue Book");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(

                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
                                                ING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
                                                        ING, false).addGroup(layout.createSequentialGroup().addGap(95, 95, 95).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
                                                                        ING, false).addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(60, 60, 60).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
                                                                        ING, false).addComponent(jTextField1).addComponent(jTextField2).addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 159,
                                                                        Short.MAX_VALUE).addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addGroup(layout.createSequentialGroup().addGap(109, 109,
                                                                109).addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jButton2))).addGroup(layout.createSequentialGroup().addGap(177, 177, 177).addComponent(jLabel5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))