/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Jframe.java to
edit this template
*/
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.Jframe;
import javax.swing.JoptionPane;
/**
 *
 * @author JAISHUK REDDY
 */
public class login extends javax.swing.Jframe {
    /**
     * Creates new form Login
     */
    public login() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the
     form.
     * WARNING: Do NOT modify this code. The content of this method is
     always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked”)
    // <editor-fold defaultstate=”collapsed” desc=”Generated Code”>
    private void initComponents() {
        jLabel1 = new javax.swing.Jlabel();
        jLabel2 = new javax.swing.Jlabel();
        jPasswordField1 = new javax.swing.JpasswordField();
        jTextField1 = new javax.swing.JtextField();
        jButton1 = new javax.swing.Jbutton();
        jButton2 = new javax.swing.Jbutton();
        jButton3 = new javax.swing.Jbutton();
        jPanel1 = new javax.swing.Jpanel();
        jLabel3 = new javax.swing.Jlabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLabel1.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username”);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
        jLabel2.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password”);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 206, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 206, -1));
        jButton1.setText("Login”);
        jButton1.addActionListener(new java.awt.event.ActionListener() {public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        jButton2.setText("Close”);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));
        jButton3.setText("Register User”);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));
        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI”, 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Library Management System”);
        jPanel1.add(jLabel3);
        getContentPane().add(jPanel1, new
                org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 290));
        pack();
    }// </editor-fold>
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

 /*if (jTextField1.getText().equals(“admin”) &&
jPasswordField1.getText().equals(“admin”)){
 setVisible(false);
 new home().setVisible(true);
 }
 else{
 jLabel4.setText(“Incorrect Username or Password !!!”);

 }*/
        String username = jTextField1.getText();
        String password = jPasswordField1.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from users where username = ‘”+username+”’ and password = ‘”+password+”’”);if(rs.next()){
                setVisible(false);
                new home().setVisible(true);
            }
            else{
                JoptionPane.showMessageDialog(null,"Incorrect username or password”);
            }
        }catch(Exception e){
            JoptionPane.showMessageDialog(null,"Incorrect username or password”);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new menu().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate=”collapsed” desc=” Look and feel
        setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with
the default look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.log ging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.log ging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.log ging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.log ging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration – do not modify
    private javax.swing.Jbutton jButton1;
    private javax.swing.Jbutton jButton2;
    private javax.swing.Jbutton jButton3;
    private javax.swing.Jlabel jLabel1;
    private javax.swing.Jlabel jLabel2;
    private javax.swing.Jlabel jLabel3;
    private javax.swing.Jpanel jPanel1;
    private javax.swing.JpasswordField jPasswordField1;
    private javax.swing.JtextField jTextField1;
    // End of variables declaration
}
