/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Jframe.java to
edit this template
*/
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JoptionPane;
/**
 *
 * @author JAISHUK REDDY
 */
public class menu extends javax.swing.Jframe {
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }
/**
 * This method is called from within the constructor to initialize the
 form.
 * WARNING: Do NOT modify this code. The content of this method isalways
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked”)
// <editor-fold defaultstate=”collapsed” desc=”Generated Code”>
private void initComponents() {
    jLabel1 = new javax.swing.Jlabel();
    jLabel2 = new javax.swing.Jlabel();
    jLabel3 = new javax.swing.Jlabel();
    jTextField1 = new javax.swing.JtextField();
    jPasswordField1 = new javax.swing.JpasswordField();
    jPasswordField2 = new javax.swing.JpasswordField();
    jButton1 = new javax.swing.Jbutton();
    jButton2 = new javax.swing.Jbutton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    jLabel1.setText("Username”);
    jLabel2.setText("Password”);
    jLabel3.setText("Confirm Password”);
    jButton1.setText("Register”);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jButton2.setText("Close”);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    javax.swing.GroupLayout layout = new
            javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(64, 64, 64).addComponent(jButton1).addGap(88, 88, 88).addComponent(jButton2)).addGroup(layout.createSequentialGroup(.addGap(40, 40, 40).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(67, 67, 67).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jTextField1).addComponent(jPasswordField1).addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 192,Short.MAX_VALUE)))).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup(.addGap(71, 71, 71).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jTextField1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(jPasswordField1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASE LINE).addComponent(jLabel3).addComponent(jPasswordField2,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(35, 35, 35).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASE LINE).addComponent(jButton1).addComponent(jButton2)).addContainerGap(70, Short.MAX_VALUE)));
    pack();
}// </editor-fold>
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password = jPasswordField1.getText();
        String confirmpassword = jPasswordField2.getText();
        if(password.equals(confirmpassword)){
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("insert into users values('"+username+"','"+password+"')”);
                JoptionPane.showMessageDialog(null,"User successfully Registered”);
                setVisible(false);
                new login().setVisible(true);
            }catch(Exception e){
                JoptionPane.showMessageDialog(null,"Exception caught : “ +e);
            }
        }
        else{
            JoptionPane.showMessageDialog(null,"Password and Confirm password do not match !!”);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate=”collapsed” desc=” Look and feel
        setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with
the default look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus”.equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logg ing.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logg ing.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logg ing.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    // Variables declaration – do not modify
    private javax.swing.Jbutton jButton1;
    private javax.swing.Jbutton jButton2;
    private javax.swing.Jlabel jLabel1;
    private javax.swing.Jlabel jLabel2;
    private javax.swing.Jlabel jLabel3;
    private javax.swing.JpasswordField jPasswordField1;
    private javax.swing.JpasswordField jPasswordField2;
    private javax.swing.JtextField jTextField1;
    // End of variables declaration
}