/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Jframe.java to
edit this template
*/
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JoptionPane;
/**
 *
 * @author JAISHUK REDDY
 */
public class newStudent extends javax.swing.Jframe {
    /**
     * Creates new form newStudent
     */
    public newStudent() {
        initComponents();
    }
/*** This method is called from within the constructor to initialize the
 form.
 * WARNING: Do NOT modify this code. The content of this method is
 always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked”)
// <editor-fold defaultstate=”collapsed” desc=”Generated Code”>
private void initComponents() {
    jPanel1 = new javax.swing.Jpanel();
    jTextField1 = new javax.swing.JtextField();
    jTextField2 = new javax.swing.JtextField();
    jTextField3 = new javax.swing.JtextField();
    jComboBox1 = new javax.swing.JcomboBox<>();
    jComboBox2 = new javax.swing.JcomboBox<>();
    jButton1 = new javax.swing.Jbutton();
    jLabel1 = new javax.swing.Jlabel();
    jButton2 = new javax.swing.Jbutton();
    jLabel2 = new javax.swing.Jlabel();
    jLabel6 = new javax.swing.Jlabel();
    jLabel3 = new javax.swing.Jlabel();
    jLabel4 = new javax.swing.Jlabel();
    jLabel5 = new javax.swing.Jlabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    jPanel1.setBackground(new java.awt.Color(0, 153, 153));
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new
            String[] { "B.Tech” }));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new
            String[] { "CSE", "IT", "Mechanical", "Civil", " " }));
    jButton1.setText("Save”);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jLabel1.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("Student ID”);
    jButton2.setText("Close”);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jLabel2.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Student Name”);
    jLabel6.setFont(new java.awt.Font("Segoe UI”, 1, 24)); // NOI18N
    jLabel6.setText("New Student Register”);jLabel3.setFont(new java.awt.Font(“Segoe UI”, 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    jLabel3.setText("Father Name”);
    jLabel4.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("Course Name”);
    jLabel5.setFont(new java.awt.Font("Segoe UI”, 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("Branch Name”);
    javax.swing.GroupLayout jPanel1Layout = new
            javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING
                    )
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(68, 68, 68)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel1,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel3,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel4,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel5,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE, 76,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                    .addGroup(jPanel1Layout."reateSequen”IalGroup()
                                            .addGap(83, 83, 83)

                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                                    .addComponent(jTextField1)
                                                    .addComponent(jTextField2)
                                                    .addComponent(jTextField3)
                                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE).addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)))

                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addComponent(jButton2)))
                            .addContainerGap(118, Short.MAX_VALUE))

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                            jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel6,
                                            javax.swing.GroupLayout.PREFERRED_SIZE, 410,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING
                    )
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField2,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField3,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox1,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox2,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42)

                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                            .addContainerGap(46, Short.MAX_VALUE))
    );
    javax.swing.GroupLayout layout = new
            javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addContainergap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                            .addContainerGap())
    );
    pack();
}// </editor-fold>
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String studentID = jTextField1.getText();
        String name = jTextField2.getText();
        String fatherName = jTextField3.getText();
        String courseName = (String)jComboBox1.getSelectedItem();
        String branchName = (String)jComboBox2.getSelectedItem();
        try{
            Connection con = ConnectionProvider.getCon();Statement st = con.createStatement();
            st.executeUpdate("insert into student values('"+studentID+"','"+name+"','"+fatherName+"','"+courseName+"','"+branchName +"')");
            JoptionPane.showMessageDialog(null,"Successfully Updated Student Details.”);
            setVisible(false);
            new newStudent().setVisible(true);
        }catch(Exception e){
            JoptionPane.showMessageDialog(null,"Student ID Already Exists”);
            setVisible(false);
            new newStudent().setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate=”collapsed” desc=” Look and feel
        setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with
the default look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus”.equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.uti
                    l.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.uti
                    l.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.uti
                    l.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.uti
                    l.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newStudent().setVisible(true);}
        });
    }
    // Variables declaration – do not modify
    private javax.swing.Jbutton jButton1;
    private javax.swing.Jbutton jButton2;
    private javax.swing.JcomboBox<String> jComboBox1;
    private javax.swing.JcomboBox<String> jComboBox2;
    private javax.swing.Jlabel jLabel1;
    private javax.swing.Jlabel jLabel2;
    private javax.swing.Jlabel jLabel3;
    private javax.swing.Jlabel jLabel4;
    private javax.swing.Jlabel jLabel5;
    private javax.swing.Jlabel jLabel6;
    private javax.swing.Jpanel jPanel1;
    private javax.swing.JtextField jTextField1;
    private javax.swing.JtextField jTextField2;
    private javax.swing.JtextField jTextField3;
    // End of variables declaration
}
